유저 그림 평가시 (GOOD, BAD) 평가 방식에서 1~5 사이의 숫자값을 받도록 수정
tipi-tapi/ai-paint-today-BE pull request #244
Opened 2023-09-25 08:34 UTC by choihuk

# 구현 내용

## 구현 요약

- Diary Entity review 타입 변경(ReviewType -> String)
  - 테이블 스키마 변경 없이 1~5 사이의 숫자값을 저장하기 위해 String 타입으로 지정했습니다.
- 실패하는 테스트 수정

## 관련 이슈

close #230 

## 구현 내용

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

2023-09-27 06:46 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
> +    IMAGE_NOT_OWNER(403, "I002", "자신의 이미지에만 접근할 수 있습니다."),
노션에 추가했습니다!

2023-09-27 06:47 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/domain/diary/domain/Diary.java
> -
diary 필드의 review는 더이상 사용되지 않을거 같기에 삭제했습니다.

2023-10-05 09:54 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
> +    IMAGE_NOT_OWNER(403, "I004", "자신의 이미지에만 접근할 수 있습니다."),
이미지 작업을 동시에 진행하면서 병합상황이 발생했기에 수정했습니다!

2023-10-05 10:28 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
> +    IMAGE_NOT_OWNER(403, "I004", "자신의 이미지에만 접근할 수 있습니다."),
노션에 추가했습니다

2023-10-05 10:30 UTC, choihuk commented on src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
> -                .willReturn("https://drawmytoday.s3.ap-northeast-2.amazonaws.com/2021-08-16/2.png");
전체 이미지 조회시 preSingnedUrl을 반환하지 않기에 해당 모킹 작업을 삭제했습니다!

2023-10-05 10:38 UTC, choihuk commented on src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
> +                .willReturn("https://test.com");
이미지 url 반환 방식 변경 부분에 대한 수정입니다!

2023-10-05 10:39 UTC, choihuk commented on src/test/java/tipitapi/drawmytoday/domain/diary/service/PromptTextServiceTest.java
> +                assertThat(promptText).contains("portrait");
기본 prompt가 emotions에서 portrait로 변경됨에 따라 수정했습니다!

2023-10-05 11:25 UTC, akalswl14 requested changes
@choihuk 코멘트 확인해주세요~

2023-10-05 11:25 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
> +            description = "성공적으로 일기를 평가함"),
일기 평가가 아니라 일기 이미지 평가라고 명세되어야 맞을 것 같아요 ~!

2023-10-05 11:25 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepository.java
> +    Optional<Image> findByImageIdAndDiaryUser(Long imageId, User user);
이미지가 이제 SoftDelete가 가능하므로 deletedAt = null 쿼리가 필요할 것 같아요. 저는 모두 queryDSL 사용하도록 했어요 (#251 , #253)

2023-10-05 11:25 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
> +    }
메서드명 Ditto 🐰

2023-10-05 11:25 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/domain/diary/service/ValidateImageService.java
> +}
이미지 삭제를 작업하면서 imageService에 validateImage 메서드를 추가했었어요. 그때는 이 외에 이미지를 검증할 일이 없을 거라 생각해서 imageService에 넣었는데 이렇게 다른 검증할 경우가 생기네요 ! imageService에 있는 validateImage 메서드는 (다른 PR에서) 옮겨와야겠네요

2023-10-05 11:25 UTC, akalswl14 commented on src/test/java/tipitapi/drawmytoday/domain/diary/controller/ImageControllerTest.java
> +        @DisplayName("review에 1~5 사이의 값이 들어오면 diaryId에 해당하는 일기를 리뷰한다.")
일기 X 이미지 or 일기이미지 Ditto 🐰

2023-10-05 11:25 UTC, akalswl14 commented on src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
> +    class ReviewDiaryTest {
메서드명 Ditto 🐰

2023-10-05 11:27 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
> +            description = "성공적으로 일기를 평가함"),
앗 바꾼다고 바꿨는데 swagger 수정은 못 했군요!

2023-10-05 11:29 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/domain/diary/domain/Image.java
> +
넵 확장성 때문도 있고 String 타입으로 해도 `@Min`이나 `@Max`같은 숫자 범위 검증 애노테이션 적용에 제약이 없어서 String 타입으로 했습니다!

2023-10-05 11:32 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/domain/diary/domain/Image.java
> +    }
넵 수정해야겠군요!

2023-10-05 11:37 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/domain/diary/domain/Image.java
> +    }
수정 완료했습니다~~

2023-10-05 11:37 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
> +            description = "성공적으로 일기를 평가함"),
수정 완료했습니다~~

2023-10-05 11:52 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepository.java
> +    Optional<Image> findByImageIdAndDiaryUser(Long imageId, User user);
넵 저도 queryDSL로 변경했습니다!

2023-10-05 11:53 UTC, choihuk commented
@akalswl14 
저도 리뷰 완료했습니다! 수정사항 전부 고쳤으니 확인 부탁드려요~

2023-10-05 11:59 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
> +    @Operation(summary = "이미지 평가", description = "주어진 ID의 일기를 평가한다.")
뒤에 description도 바꾸면 좋을 것 같습니다 !

2023-10-05 12:03 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
> +    @Operation(summary = "이미지 평가", description = "주어진 ID의 일기를 평가한다.")
변경했습니다!

2023-10-05 12:03 UTC, akalswl14 approved these changes

2023-10-05 12:03 UTC, merged