소셜로그인 오류 해결 및 리팩토링
tipi-tapi/ai-paint-today-BE pull request #51
Opened 2023-06-17 12:17 UTC by choihuk

# 구현 내용

__구글, 애플 소셜로그인(회원가입), 회원탈퇴 기능 리팩토링 및 테스트 완료__

## 구현 요약

- 소셜로그인 성공시 유저의 이메일 대조 뿐만 아니라 delete 유무까지 확인하여 회원가입한 유저인지 체크하도록 변경

- 구글, 애플 소셜로그인 탈퇴 기능 구현
  - 탈퇴 요청 성공시 소셜로그인 탈퇴
  - 탈퇴 요청 성공시 유저를 db에서 삭제하는 것이 아닌 deletedAt으로 탈퇴 시각을 저장하도록 구현(재 회원가입시 새로운 유저 생성)

- 프론트에서 탈퇴 요청을 보낼 때 토큰 만료시 access token 재발급 요청을 먼저 보내 토큰을 재발급받고, 탈퇴 요청을 보내는 시나리오 테스트 완료

- swagger에 oauth 요청시 발생할 수 있는 모든 에러 명시 완료

- 에러 메시지 인코딩 실패 오류 해결

- user 엔티티에 oauth_type 필드 삭제(social_code와 중복)
```
로컬 서버에도 적용해주세요!
alter table user drop oauth_type;
```

## 관련 이슈

close #21 #44 

## 구현 내용

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-06-17 12:17 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
> +        "/oauth2/refresh"
uri가 잘못되어 있어 수정했습니다.

2023-06-17 12:18 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
> +    }
RestTemplate으로 rest 통신 시 발생하는 에러를 잡기 위해 만들었습니다.

2023-06-17 12:19 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
> +            response.setCharacterEncoding("UTF-8");
인코딩 설정을 안 해서 한글이 ???로 깨졌었습니다.

2023-06-17 12:21 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
> +    }
controllerAdvice에서 에러 response 반환 형식과 동일하도록 변경했습니다.

2023-06-17 12:22 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> -    // }
로그아웃은 프론트와 논의 후 추후에 구현하도록 하고 지금은 지우겠습니다.

2023-06-17 12:26 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/user/domain/User.java
> -    private OAuthType oauthType;
oauthType 필드 삭제했습니다. (socialCode 중복)

2023-06-17 12:29 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/user/domain/User.java
> +    private LocalDateTime deletedAt;
deleteAt을 구현하여 유저가 탈퇴한 시각을 저장했습니다.

2023-06-17 12:30 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/user/service/UserService.java
> +public class UserService {
UserService를 만든 이유는 회원가입하는 로직을 소셜로그인하는 메서드로부터 분리하기 위함입니다.

2023-06-20 05:06 UTC, akalswl14 requested changes
@choihuk 고생하셨습니다~ 코멘트 확인 부탁드려요~~

2023-06-20 09:36 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
> +    }
RestTemplate을 OAuth만 사용하는 것이 아니기에 OAUTH_SERVER_FAILED는 잘못된 에러 코드로 보입니다. REST_CLIENT_FAILED로 바꾸겠습니다.

2023-06-20 09:37 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/user/domain/User.java
> -    private OAuthType oauthType;
넵 다른 곳에서도 사용하지 않기에 삭제하는것이 좋다고 생각하여 삭제했습니다.

2023-06-20 15:01 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
> +    }
네, 추가적인 질문 드릴게요!

현재 일기 생성 시에는 DALL-E 처리가 실패할 것에 따른 예외 처리가 되어 있습니다. HttpClientErrorException가 발생하면 DallERequestFailException를 던지는 구조 입니다. 

![image](https://github.com/tipi-tapi/ai-paint-today-BE/assets/42285463/172ba5d6-da15-40ff-8548-abbec59ba82c)
그런데 위와 같이 RestClientException은 HttpClientErrorException의 부모 예외라서, handleRestClientException 메소드가 HttpClientErrorException 에러 핸들링을 처리해서 DallERequestFailException를 던지지 못하게 되나요?

2023-06-20 15:18 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
> +    }
제가 알기로 ControllerAdvice는 컨트롤러 메서드에서도 처리하지 못한 에러들을 공통으로 잡아 핸들링하는 것으로 알고 있어 서비스단에서 던진 에러를 잡지는 않는다고 생각합니다.

따라서 DallEService의 getImageAsUrl메서드가 실행 중 HttpClientErrorException 에러가 발생해도 controllerAdvice가 아닌 try catch 문에 의해 바로 잡히고 새로운 커스텀 에러로 변환되어 던져진다고 이해하고 있습니다.

2023-06-21 04:53 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
> +    }
넵 이해하였습니다, 감사합니다~

2023-06-21 04:53 UTC, akalswl14 approved these changes

2023-06-21 04:53 UTC, merged