JWT 토큰 만료 API(테스트용)
tipi-tapi/ai-paint-today-BE pull request #59
Opened 2023-06-23 14:23 UTC by choihuk

# 구현 내용

## 구현 요약

- 테스트용 JWT 토큰 만료 API 구현
- request header 안에 토큰 가져오는 로직 통일화

## 관련 이슈

close #53 

## 구현 내용

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-06-23 14:25 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
> +    JWT_TOKEN_NOT_FOUND(404, "S008", "jwt token이 없습니다."),
JWT access token과 refresh token 구분 없이 토큰이 없을 경우 반환되는 에러를 따로 만들었습니다.

2023-06-23 14:26 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtProperties.java
> +    public static final String JWT_TOKEN_HEADER = "Authorization";
jwt access token이나 refresh token 모두 Authorization 헤더에서 가져오고, 앞으로도 계속 변하지 않을 것이라 생각하기에 통일했습니다.

2023-06-23 14:29 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtType.java
> +    ACCESS, REFRESH, BOTH
Jwt의 type에 따라 access token인지, refresh token인지, 둘 다 상관 없는지에 따라 동작이 조금씩 달라지는 메서드를 공통으로 처리하기 위해 만들었습니다.

2023-06-23 14:33 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> +        String refreshToken = HeaderUtils.getJwtToken(request, JwtType.REFRESH);
refresh token도 공통 메서드로 추상화했습니다.

2023-06-26 03:40 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtType.java
> +    ACCESS, REFRESH, BOTH
둘 다 상관없는지는 어떤 경우 인가요?

2023-06-26 03:47 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> +    @GetMapping("/expiredJwt")
API URI에는 대문자는 지양해야한다고 생각합니다.
일반적으로 REST API URI를 설계할때 소문자로 작성하는 컨벤션을 적용하는데, 대문자가 때때로 문제를 일으키는 경우가 있기 때문입니다.

2023-06-26 03:48 UTC, akalswl14 requested changes
@choihuk 
리뷰와, 변경 요청 코멘트를 작성하였으니 확인부탁드립니다~

2023-06-26 05:57 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtType.java
> +    ACCESS, REFRESH, BOTH
지금처럼 토큰 만료 API에서 요청받은 토큰이 ACCESS인지 REFRESH인지에 상관없이 만료시키는 로직일 경우 하나의 타입을 지정하는게 의미상 혼선이 생길 수 있을거 같아 BOTH를 만들었습니다.

2023-06-26 05:58 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> +    @GetMapping("/expiredJwt")
그렇군요! snake case로 변경하겠습니다

2023-06-26 06:51 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> +    @GetMapping("/expiredJwt")
snake case보다는 dash case가 맞다고 생각합니다.
그리고, 굳이 _든, -든 넣지 않아도 되지 않을까요? /expire로만 해도 충분해 보입니다.

2023-06-26 06:52 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
예외가 추가, 변경되었을 경우 노션에 반영해주세요!

2023-06-26 07:15 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> +    @GetMapping("/expiredJwt")
저는 무엇을 expire할지까지 uri에 있어야되지 않을까? 라는 생각으로 uri를 설계했는데 이미 api 명세에 jwt 토큰을 헤더에 넣는다는 설명이 있으니 굳이 jwt까지 명시하지 않아도 될 듯 하네요

수정하겠습니다.

2023-06-26 07:29 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> +    @GetMapping("/expiredJwt")
jwt 토큰을 헤더에 넣는다는 설명이 어디에 있는 부분을 말하는건지 찾지 못했는데, 만약 그런거라면 /jwt/expire 처럼 /로 구분해도 좋을 것 같아요

2023-06-26 10:06 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> +    @GetMapping("/expiredJwt")
swagger에 jwt 토큰이 필요하다는 설정을 추가하고 uri는 expire로 변경하겠습니다!

2023-06-26 10:06 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
알겠습니다!

2023-06-26 10:52 UTC, choihuk commented
@akalswl14 
토큰 만료 api uri 수정했습니다.

swagger security scheme 등록 방식을 bean configuration에서 annotation 등록 방식으로 변경했습니다.
빈으로 등록시 그룹 단위가 아닌 개별 단위의 설정 변경이 어렵기에 해당 방식으로 변경했고, 도메인의 모든 api가 토큰을 필요로 하면 class단에애노테이션을 등록하여 공통 처리했습니다.

2023-06-26 12:27 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
> +        security = @SecurityRequirement(name = "Bearer Authentication"))
회원 탈퇴도 jwt token이 필요할텐데, security 설정이 추가되어야할 것 같아요~!

2023-06-26 12:28 UTC, akalswl14 requested changes
@choihuk 
swagger 설정이 깔끔하게 바뀌었네요! 회원 탈퇴부분만 반영부탁드려요~

2023-06-26 13:22 UTC, choihuk commented
@akalswl14 
회원 탈퇴부분 반영했고 월별 일기 목록 api에 쿼리 파라미터 명세 추가도 완료했습니다!

2023-06-26 13:53 UTC, akalswl14 approved these changes

2023-06-26 13:54 UTC, merged