JWT, OAuth 구현
tipi-tapi/ai-paint-today-BE pull request #9
Opened 2023-04-27 07:47 UTC by choihuk

# 구현 내용

## 구현 요약

- 내부적으로 사용하는 JWT 구현
- OAuth2 Google 인증로직 구현
- 로그인시 필요한 Repository 구현
- application.oauth 설정 추가
- Security 관련 에러코드 추가 및 에러클래스 추가
- AuthController Swagger 추가

## 관련 이슈

close #8 
#12 
#13 

## 구현 내용

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---
## 참고사항

-  노션 내부자료에 jwt secret을 application-oauth 파일에 넣어야 동작합니다.
- url: "/refresh", "/delete" => "/oauth2/refresh", "/oauth2/delete"로 변경되었습니다.
- 변경된 컨벤션에 따라 애플 로그인시 android 지원 코드 삭제했습니다.(requestAppleLogin 클래스의 osPlatform 파라미터 삭제)
- JWT, OAuth 클래스 설명은 양이 너무 많을 거 같아 노션에 정리해서 올리겠습니다.

2023-04-27 16:36 UTC, akalswl14 requested changes
@choihuk 
우선 PR에 관한 규칙이 좀 필요할 것 같아!
#11 확인하고, 머지 후에 rebase해서 코드 포맷팅 바뀐거 이 브랜치에도 반영해줘!

아래는 내가 생각한 규칙이야. 보고, 추가적인 부분이 있으면 또 코멘트 달아주고, 없다면 아래 규칙대로 한번 더 개선을 부탁할게! 그 후에 다시 코드 리뷰 할게!
1. 코드 작성자는 최대한 코멘트를 남긴다. 기본적인 코드가 아닌 이상, 특히, 새로운 기능, 새로운 클래스 등은 코드에 대한 설명으로 코멘트를 남긴다.
    - EX) Security 코드
2. 이번에 작업하면서 한계가 있었던 부분은 코멘트를 남기고, 리뷰어도 생각하여 의견을 남긴다. 해결되지 않았을 경우, 별도의 이슈로 등록한다.
3. 이번에 작업하면서 고민했던 부분을 코멘트를 남긴다.
4. 주석은 두가지 종류로 분류한다.
    1. 꼭 필요한 경우에 한해, 코드에 대한 간략한 설명
    2. 미처 구현하지 못한 점, 추후 개선해야하는 점은 ‘// TODO : 내용’ 의 형식으로 남긴다. ( 구어체 X )
5. 주석을 남긴 부분은 PR 코멘트에 왜 주석을 남겼는지 작성한다.
6. 코드 포맷팅으로 인한 변화는 가능하면, 별도의 PR로 남긴다. 
    1. 그렇지 않으면 가독성이 떨어져, 로직 변화에 대한 리뷰에 집중하기가 어렵다.
7. PR 제출 전(혹은 리뷰 요청 전), import 최적화, code format, 불필요한 공백(엔터)는 없는지 확인한다.

2023-05-02 15:31 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
> +
ㅁㅇㄹㅁㄴㅇ

2023-05-05 08:12 UTC, doorBW commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
> +    AUTHORITY_NOT_FOUND(404, "S001", "Authority not found"),
다른 error message들은 한글로 되어있어서, 한글로 할지 영어로 할지 통일하면 좋을 것 같습니다.

2023-05-05 08:16 UTC, doorBW commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/AppleOAuthService.java
> +        String url = "https://appleid.apple.com/auth/revoke";
static으로 빼거나 properties로 관리하면 좋을 것 같습니다.

2023-05-05 08:16 UTC, doorBW commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/AppleOAuthService.java
> +        String appleTokenUrl = "https://appleid.apple.com/auth/token";
ditto

2023-05-05 08:16 UTC, doorBW commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/GoogleOAuthService.java
> +        String url = "https://oauth2.googleapis.com/revoke";
ditto

2023-05-05 08:16 UTC, doorBW commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/GoogleOAuthService.java
> +        String tokenUri = "https://oauth2.googleapis.com/token";
ditto

2023-05-08 15:10 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
> +    AUTHORITY_NOT_FOUND(404, "S001", "Authority not found"),
동감합니다. 이 부분 논의가 필요할 것 같습니다.
@choihuk

2023-05-08 15:14 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
> +    AUTHORITY_NOT_FOUND(404, "S001", "Authority not found"),
저도 통일하는게 좋을 것 같습니다.

2023-05-08 15:42 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/GoogleOAuthService.java
> +        String url = "https://oauth2.googleapis.com/revoke";
ditto2

2023-05-08 15:42 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/GoogleOAuthService.java
> +        String tokenUri = "https://oauth2.googleapis.com/token";
ditto2

2023-05-09 08:27 UTC, akalswl14 requested changes
일단, 로그인 이후 인증 과정과 기타 사항에 대해 리뷰를 남겨요!
확인 후에 답변 부탁드립니다 ~!

DB 이름과 같이 제가 미처 컨벤션을 지키지 못한 부분도 수정해주셔서 감사합니다.

Spring Security에 깊은 이해가 있는 것이 아니라서, 컨벤션 적인 것이나 내부 구조인 부분인데 리뷰를 남긴 부분이 있을 수도 있을 것 같아요. 이 부분은 양해를 부탁드리고, 해당 부분은 간단히 답변 남겨주시면 이해한 뒤  추가적인 의견 남기겠습니다 😭 

남은 코드들은 내일 오전 중으로 리뷰 마치겠습니다! 수고하셨습니다 😸

2023-05-09 08:27 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
> +    }
이 생성자는 쓰이지 않는 것으로 보이는데, 내부적으로 사용되는 건가요?

2023-05-09 08:27 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
> +    }
저희가 지난번에 유저의 권한과 관련해서 확장을 고려해서 유지할지, 제거할지 논의했었던 것 같은데 결론이 잘 기억나지 않습니다.
저는 유저 권한이 필요하도록 확장하지 않을 것 같다고 말씀드렸던 것은 기억이 나는데, 결론적으로는 코드 상에서 유지하는 것으로 논의했었나요?
만약 폐기하는 방향으로 논의했다면 이 생성자의 세번째 파라미터는 없는게 맞지 않을까 생각이 듭니다.

2023-05-09 08:27 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtTokenProvider.java
> +        }
위에서 말씀 드린 유저 권한과 관련된 부분 코멘트 남깁니다.
권한 있도록 확장하지 않도록 논의했다면, 이부분도 없어져야 맞지 않나 생각됩니다.

2023-05-09 08:27 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
> +                "can't change authenticate because authenticate already true");
에러 메시지를 한국어로 작성하는 것이 일관적일 것 같습니다 :)

2023-05-09 08:27 UTC, akalswl14 commented on src/main/resources/application-oauth.yml
> +        client-secret:
이 값은 어디에 있나요? 저희 노션에 있나요??
애플 Client ID는 찾았는데 구글은 안보여서요.

2023-05-09 08:27 UTC, akalswl14 commented on src/main/resources/application-oauth.yml
> +    secret:
이런 보안 값은 실행 전에 입력해줘야하는 값일 것같아서 README.md에 명세해주면 좋지 않을까 생각이 듭니다!

그리고, 이런 값들은 개발 시에, 실행 전에 입력해두고, 깃에는 커밋되어야하지 않아야하는 값인데, 커밋 할때마다 제외되었는지 확인하는 과정이 번거로울 것 같아요. 그래서, 이렇게 공백으로 두기 보다는 ${변수명} 이런 식으로 입력해서 인텔리제이에 환경변수로 등록할 수 있는 방법이 좋을 것 같아요.

2023-05-09 17:20 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/resolver/AuthUser.java
> +}
이 인터페이스는 @AuthUser 어노테이션에 대한 인터페이스인 것 같은데, 이 코드가 무슨 역학을 수행하는지 직관적으로 알기가 어려워요. 이 코드는 우리가 논의했던 부분을 기억하고, AuthUserArgumentResolver를 봐야함 이해할 수 있을 것 같아요!
( 물론 지금은 이해했습니다. 아래는 앞으로의 PR시 제안입니다. )

앞으로는 이 코드와 같이, 새롭게 추가된 내용은 이슈 구현 내용에 적어주시고, 이 코드의 single comment에 어떤 역할 혹은 목적에 대한 코드인지 간략한 설명 남겨주시면 좋을 것 같습니다.

2023-05-10 00:33 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
> +    }
저희는 소셜 서버와 rest 통신 목적으로 사용합니다. 따로 oauthConfig 파일이 없기에 이곳에 등록했습니다.

2023-05-10 00:35 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
> +public class JwtAuthenticationEntryPoint extends OncePerRequestFilter {
넵 Spring Security는 필터단에서 동작하기에 예외 발생 시 예외를 처리하여 넘길 클래스가 별도로 필요하며, 이 클래스를 Endpoint라 부르는 것으로 알고 있습니다.

2023-05-10 00:38 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
> +                "can't change authenticate because authenticate already true");
저도 그렇게 생각합니다 수정하겠습니다

2023-05-10 00:39 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
> +    }
권한이 없는 토큰을 만들 때 사용할 생성자입니다. 원래는 사용되지 않았으나 저희 정책상 유저의 권한이 필요없기에 사용될 것 같습니다.

2023-05-10 00:43 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
> +    }
저는 다음 pr에서 제거하기로 논의된 것으로 기억합니다. 다음 pr에서 유저 권한 관련 코드를 모두 삭제하겠습니다.

2023-05-10 00:43 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
> +    }
또한 이 생성자도 삭제하겠습니다

2023-05-10 00:44 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtTokenProvider.java
> +        }
네 이 부분도 없어집니다.

2023-05-10 00:46 UTC, choihuk commented on src/main/resources/application-oauth.yml
> +        client-secret:
저희 티피타피 계정으로 구글 api로 들어가면 웹클라이언트에 있습니다. 노션에도 따로 올리겠습니다.

2023-05-10 00:51 UTC, choihuk commented on src/main/resources/application-oauth.yml
> +    secret:
저도 환경변수로 관리하는 것이 더 좋을 것 같습니다. 토큰 만료 시간에 대해 논의된 사안이 없기에 임시값을 넣었고, 컨벤션이 정해지면 README에 명세하겠습니다.

2023-05-10 01:06 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
> +            .headers().disable()
예전에 h2 console 실행 시 헤더 보안때문에 실행이 안 되어 추가한 것 같습니다. 지금은 어떤 기본 보안 헤더를 disable할지 명시하지 않았기에 추가적인 동작은 없겠으나 제거하는게 맞을 것 같습니다.

2023-05-10 01:27 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/resolver/AuthUser.java
> +}
구현 내용에 대해 논의할 사항이 생길 수 있는 부분은 전부 이슈로 등록하고 설명이 필요한 부분은 코멘트로 남기는 것으로 이해해도 될까요?

2023-05-10 01:28 UTC, choihuk reviewed
1차 리뷰에 대한 답변 올렸습니다. 코드 변경까지 완료되면 알람 드리겠습니다.

2023-05-10 06:24 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/resolver/AuthUser.java
> +}
전..부라는 단어가 조금 무섭기는 한데 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ,,, 맞습니다!
회의로 논의하면 좋기는한데,, 시간 맞추기도 쉽지도 않고, 논의 사항을 기록하는 목적으로도 좋을 것 같고, PR 분리에도 좋다고 생각해요!

설명이 필요한 부분을 코멘트로 남기는 것도 맞습니다!

2023-05-10 06:24 UTC, akalswl14 commented on src/main/resources/application-oauth.yml
> +    secret:
지금은 토큰 만료 시간 얼마로 생각하고 개발하셨나요??

2023-05-10 06:24 UTC, akalswl14 commented on src/main/resources/application-oauth.yml
> +        client-secret:
감사합니다~

2023-05-10 06:25 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
> +public class JwtAuthenticationEntryPoint extends OncePerRequestFilter {
네넵 감사함당 이 리뷰는 종결 시킬게용

2023-05-10 06:37 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
> +    }
확인하였습니다~ 다음 PR에서 반영되는 것으로 알고, resolve 하겠습니다~~!

2023-05-10 06:37 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtTokenProvider.java
> +        }
확인하였습니다~ 다음 PR에서 반영되는 것으로 알고, resolve 하겠습니다~~!

2023-05-10 08:02 UTC, choihuk commented on src/main/resources/application-oauth.yml
> +    secret:
지금은 access token은 50시간, refresh token은 70일로 잡아두었습니다. 보통 앱에서 사용하는 jwt 토큰은 만료시간을 어떻게 잡는게 좋을지 잘 모르겠어서 이렇게 했습니다.

2023-05-10 08:41 UTC, akalswl14 requested changes
컨트롤러 부분에 대한 1차 리뷰 입니다~ 확인 후 답변 부탁드려요!

2023-05-10 08:41 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +        log.info("jwtToken = {}", jwtToken);
만약, jwtToken을 로그로 남길 필요가 없다면, 별도의 변수로 만들 필요없이 바로 리턴하면 좋을 것 같아요

2023-05-10 08:41 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +        log.info("apple login");
그리고, 애플 로그인은 로그를 남기는게 구글로그인과 상이한데 이유가 있나요?

2023-05-10 08:41 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/dto/UserProfile.java
> +public class UserProfile {
소셜에서 받아오는 프로필 정보 맞나요? 추후 저희 서비스의 유저 프로필 도메인과 구분하기 위해서는 클래스명이 OAuthUserProfile 처럼 다르게 하는 것이 좋을 것 같아요

2023-05-10 09:26 UTC, akalswl14 requested changes
라이브 코드 리뷰 중 논의한 리뷰를 추가합니다!

2023-05-10 09:26 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/GoogleOAuthService.java
> +            .orElseThrow(() -> new RuntimeException("User refresh token not found"));
별도의 ErrorCode를 가진 예외로 처리하는 것이 좋아 보입니다.

2023-05-10 09:26 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/dto/ResponseAccessToken.java
> +public class ResponseAccessToken {
내부적으로 소셜과 통신하여 받아오는 access token이니까, OAuthAccessToken와 같은 네이밍은 어떨까요?

2023-05-10 10:04 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +package tipitapi.drawmytoday.common.security.oauth2.controller;
security oauth client로 구현 도중 포기하고 수작업으로 oauth를 구현하다보니 패키지 구성이 이렇게 되었네요 ㅎㅎ;;
security에서 사용하는 용도이나, oauth도 도메인처럼 컨트롤러, 서비스, 리포지토리 구조를 가져가니 도메인으로 빼는 것이 맞을 것 같습니다.

2023-05-10 10:04 UTC, choihuk commented on src/main/resources/application-develop.yml
> +    url: jdbc:mysql://localhost:3306/draw_my_today_db?serverTimezone=UTC&characterEncoding=UTF-8
알겠습니다.

2023-05-10 10:31 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +        log.info("apple login");
로그 삭제했습니다.

2023-05-10 10:32 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/GoogleOAuthService.java
> +        log.info("accessToken: {}", objectMapper.writeValueAsString(accessToken));
로그 삭제했습니다.

2023-05-10 10:32 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +        log.info("delete account");
ditto: 로그 삭제

2023-05-10 10:35 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/resolver/AuthUserArgumentResolver.java
> +        return tokenInfo;
변수 합쳤습니다.

2023-05-10 10:36 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +            throw new RuntimeException("해당 사용자는 OAuth2 로그인이 아닙니다.");
저희 컨벤션인 커스텀 에러로 최대한 처리하는 것이 일관성면에서 좋을 것 같습니다.

2023-05-10 10:37 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +            () -> new IllegalArgumentException("해당 사용자가 존재하지 않습니다. id=" + tokenInfo.getUserId())
IllegalArgumentException도 커스텀 에러로 처리하는 방향이 옳은 것 같습니다.

2023-05-10 11:21 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/GoogleOAuthService.java
> +        RestTemplate restTemplate = new RestTemplate();
수정했습니다.

2023-05-10 11:22 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/GoogleOAuthService.java
> +            .orElseThrow(() -> new RuntimeException("User refresh token not found"));
수정했습니다!

2023-05-10 11:22 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/service/AppleOAuthService.java
> +            throw new RuntimeException("Failed to delete account");
수정했습니다.

2023-05-10 11:26 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/dto/ResponseJwtToken.java
> +public class ResponseJwtToken {
라이브 코딩 리뷰에서 논의한대로 서버와 소셜서버간의 dto는 Response나 Request를 안 붙이는 것으로 바꾸겠습니다.

2023-05-10 11:28 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/dto/UserProfile.java
> +public class UserProfile {
넵 OAuthUserProfile이 좋을 것 같습니다.

2023-05-10 11:33 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/dto/ResponseJwtToken.java
> +public class ResponseJwtToken {
ResponseAccessToken을 OAuthAccessToken으로 바꾸어 차이를 명확히 나타냈습니다. resolve하겠습니다!

2023-05-10 11:39 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +    public ResponseJwtToken getAccessToken(HttpServletRequest request) {
별도의 ResponseAccessToken을 만들었습니다!

2023-05-10 11:40 UTC, choihuk commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/dto/ResponseJwtToken.java
> +@Schema(description = "accessToke, refreshToken Response")
수정했습니다!

2023-05-13 06:48 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/user/controller/AuthController.java
> +public class AuthController {
좋습니다~

2023-05-13 06:50 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +            throw new RuntimeException("해당 사용자는 OAuth2 로그인이 아닙니다.");
저는 400대 에러라고 생각해요
서버에서 로그인 수단을 제공하지 않으니, 올바르지 않은 수단으로 로그인한 클라이언트 측 예외라고 봅니다

2023-05-13 06:53 UTC, akalswl14 commented
> 에러 메시지 한글화, 로그 제거와 같은 단순 변경은 수정 이후 바로 resolve conversation했고, 논의가 있을 것 같은 코멘트는 수정 이후 안 닫았습니다. 
> 
> 
> 
> response dto 필드에 final 키워드 추가와 @NotBlank 애노테이션 추가했습니다. 
> 
> request dto 또한 추가하려 했으나, 잭슨 라이브러리가 클래스를 만들 때 NoArgsConstructor가 필요하기에 필드에 final 키워드를 사용할 수 없습니다. 그렇기에 저는 final 키워드 없이 @NotBlank 애노테이션만 넣는게 좋을 것 같습니다. 혹시 어떻게 생각하시나요?

동의합니다~~

2023-05-13 07:02 UTC, akalswl14 approved these changes

2023-05-13 07:03 UTC, akalswl14 commented
@choihuk 
기나긴 PR이 끝났네요! 
오늘 미팅때 논의할거 있는지 한번 더 확인하고, 머지합시다!
수고하셨습니다 😀

2023-05-13 11:10 UTC, akalswl14 commented on src/main/resources/application-oauth.yml
> +    secret:
@choihuk 
gpt와의 논의 결과 : acccess token - 1시간, refresh token - 60일 로 정하였습니다!

2023-05-13 11:17 UTC, akalswl14 commented on src/main/java/tipitapi/drawmytoday/common/security/oauth2/controller/AuthController.java
> +            throw new RuntimeException("해당 사용자는 OAuth2 로그인이 아닙니다.");
이해했습니다! 삭제 시였군요! 500 서버 에러가 맞는 것 같습니다!

2023-05-13 11:19 UTC, akalswl14 approved these changes

2023-05-13 11:19 UTC, merged